lo:
  api-key: YOUR_API_KEY
  api-url: https://liveobjects.orange-business.com/api
  
  uri: ssl://liveobjects.orange-business.com:8883
  username: application

  clientId: mqtt2iot
  recovery-interval: 10000
  completion-timeout: 20000
  connection-timeout: 30000
  qos: 1
  keep-alive-interval-seconds: 0
  page-size: 20
  
  synchronization-device-interval: 10000
  
azure-iot-hub-list:
  -
    iot-connection-string: YOUR_IOT_CONNECTION_STRING
    iot-host-name: YOUR_IOT_HOST_NAME
    synchronization-thread-pool-size: 40
    device-client-connection-timeout: 5000
    tagPlatformKey: platform
    tagPlatformValue: LiveObjectsGroup1
    
    lo-messages-topic: MESSAGES_TOPIC
    lo-devices-topic: DEVICES_TOPIC
    lo-devices-group: DEVICES_GROUP

  -
    iot-connection-string: YOUR_IOT_CONNECTION_STRING
    iot-host-name: YOUR_IOT_HOST_NAME
    synchronization-thread-pool-size: 40
    device-client-connection-timeout: 5000
    tagPlatformKey: platform
    tagPlatformValue: LiveObjectsGroup2
    
    lo-messages-topic: MESSAGES_TOPIC
    lo-devices-topic: DEVICES_TOPIC
    lo-devices-group: DEVICES_GROUP
  
azure:
  application-insights:
    instrumentation-key: YOUR_INSTMENTATION_KEY
    channel:
      in-process:
        developer-mode: true
        max-telemetry-buffer-capacity: 500
        flush-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: Lo2IotHub