lo:
  api-key: YOUR_API_KEY
  api-url: https://liveobjects.orange-business.com/api
  
  uri: ssl://liveobjects.orange-business.com:8883
  username: application
  
  messages-topic: messages
  devices-topic: devices
  
  clientId: mqtt2iot
  recovery-interval: 10000
  completion-timeout: 20000
  connection-timeout: 30000
  qos: 1
  keep-alive-interval-seconds: 0
  page-size: 20
  
azure:
  iot-connection-string: YOUR_IOT_CONNECTION_STRING
  iot-host-name: YOUR_IOT_HOST_NAME
  synchronization-device-interval: 10000
  synchronization-thread-pool-size: 40
  messaging-thread-pool-size: 40
  device-client-connection-timeout: 5000
  tagPlatformKey: platform
  tagPlatformValue: LiveObjects
  application-insights:
    instrumentation-key: YOUR_INSTMENTATION_KEY
    channel:
      in-process:
        developer-mode: true
        max-telemetry-buffer-capacity: 500
        flush-interval-in-seconds: 5
spring:
  application:
    name: Lo2IotHub